Fix docker entrypoint exiting with '0' with failing tests
The whole script doesn't have a 'set -e' at the top, so when we added
pypy tests it had the side-effect of exiting with a 0 status even if
first group of nosetests were failing.

diff --git a/docker/run b/docker/run
--- a/docker/run
+++ b/docker/run
@@ -18,6 +18,9 @@ elif [ "$1" == "test" ]; then
 	echo "Elastic search already installed"
   fi
   sudo service elasticsearch start
+  #fail from now if tests fail
+  set -e
+  #run tests
   nosetests -e '.*integration.*'
   /virtualenv/pypy/bin/nosetests tests/utils/test_{kvstore,decorator,dict}.py
 else
